import React from 'react';

export default function Disclaimer({ onClose }: { onClose: () => void }) {
  return (
    <div className="max-w-3xl mx-auto p-12 bg-white text-black border border-black my-8 relative">
      <button 
        onClick={onClose}
        className="absolute top-6 right-6 text-xs uppercase tracking-widest text-zinc-400 hover:text-black font-semibold"
      >
        [Close]
      </button>

      <h1 className="editorial-title text-3xl font-light mb-8 border-b border-black pb-4">
        Disclaimer
      </h1>

      <div className="space-y-6 font-serif italic text-zinc-700 leading-relaxed text-sm">
        <p>
          The information, calculations, and operational metrics generated by the Alluvial Site Manager application are provided "as is" for organizational utility and record-keeping purposes.
        </p>

        <h3 className="font-semibold text-black uppercase tracking-wider text-xs not-italic mt-8">No Operational Warranties</h3>
        <p>
          While we implement automated validation scripts for fuel stock reconciliation and daily gold recovery weights, all calculations must be verified by on-site controllers. Alluvial Africa does not warrant the absolute mathematical precision of dynamic metrics under all operating environments.
        </p>

        <h3 className="font-semibold text-black uppercase tracking-wider text-xs not-italic mt-8">Regulatory Compliance</h3>
        <p>
          It is the tenant's responsibility to verify that all shift logs, gate registers, and staff attendance records comply with local labor, environmental, and mining regulatory requirements in their respective jurisdictions.
        </p>
      </div>

      <div className="mt-12 pt-6 border-t border-zinc-200 text-center">
        <button onClick={onClose} className="minimal-btn">
          Acknowledge
        </button>
      </div>
    </div>
  );
}
