import { SESClient, SendEmailCommand } from '@aws-sdk/client-ses';

const ses = new SESClient({});
const FROM_EMAIL = process.env.SES_FROM_EMAIL || 'reports@alluvial.africa';

const TEMPLATE_NAMES: Record<string, string> = {
  TEMPLATE_01: 'Site Daily Summary',
  TEMPLATE_02: 'Staff Attendance & Shift Roster',
  TEMPLATE_03: 'Excavator / Machine Daily Log',
  TEMPLATE_04: 'Fuel Issuance & Reconciliation',
  TEMPLATE_05: 'Mining & Geology Daily Sheet',
  TEMPLATE_06: 'Drum & Sand Pump Shift Log',
  TEMPLATE_07: 'Centrifuge Operation & Cleanup Log',
  TEMPLATE_08: 'Shaking Table Operation Log',
  TEMPLATE_09: 'Gold Recovery & Handover Register',
  TEMPLATE_10: 'Maintenance, Greasing & Washing Log',
  TEMPLATE_11: 'Gate, Search & Items Movement Register',
  TEMPLATE_12: 'Stores, Purchases & Expense Sheet',
  TEMPLATE_13: 'Shift Handover Certificate',
  TEMPLATE_14: 'HR Payroll & Leave Record',
  TEMPLATE_15: 'Petty Cash Daily Report',
};

function escapeHtml(str: any): string {
  if (str === null || str === undefined) return '';
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function generateEmailHtml(body: any): string {
  const templateName = TEMPLATE_NAMES[body.reportType] || body.reportType;
  const dateStr = body.submittedAt ? new Date(body.submittedAt).toLocaleString() : 'N/A';

  let parsedData: Record<string, any> = {};
  try {
    parsedData = typeof body.reportData === 'string' ? JSON.parse(body.reportData) : (body.reportData || {});
  } catch {
    parsedData = {};
  }

  const fieldRows = Object.entries(parsedData)
    .filter(([k]) => !['rows', 'secondaryRows', 'signature', 'signatures', '__id'].includes(k))
    .filter(([, v]) => typeof v !== 'object' || v === null)
    .map(([k, v]) => `<tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">${escapeHtml(k)}</td><td style="padding:8px;border:1px solid #ddd;">${typeof v === 'boolean' ? (v ? 'Yes' : 'No') : escapeHtml(v)}</td></tr>`)
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Georgia', serif; padding: 20px; color: #111; }
    h1 { font-weight: normal; font-size: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
    .meta { margin: 15px 0; font-family: sans-serif; font-size: 13px; color: #444; }
    .meta p { margin: 3px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    .footer { margin-top: 30px; font-size: 11px; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }
  </style>
</head>
<body>
  <h1>Titan Mining - ${escapeHtml(templateName)} Report</h1>

  ${body.message ? `<p style="margin:15px 0;padding:10px;background:#f9f9f9;border-left:3px solid #000;font-style:italic;">${escapeHtml(body.message)}</p>` : ''}

  <div class="meta">
    <p><strong>Organization:</strong> ${escapeHtml(body.orgId)}</p>
    <p><strong>Site:</strong> ${escapeHtml(body.siteId || 'N/A')}</p>
    <p><strong>Submitted By:</strong> ${escapeHtml(body.userId)}</p>
    <p><strong>Date:</strong> ${dateStr}</p>
    <p><strong>Status:</strong> ${escapeHtml(body.status)}</p>
  </div>

  <table>
    <thead>
      <tr style="background:#f4f4f4;">
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Field</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Value</th>
      </tr>
    </thead>
    <tbody>${fieldRows}</tbody>
  </table>

  <div class="footer">
    <p>This report was automatically generated by Titan Mining Site Manager.</p>
    <p>Powered by Alluvial Africa / ChatWorks</p>
  </div>
</body>
</html>`;
}

export const handler = async (event: any) => {
  const headers = {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
  };

  if (event.requestContext?.http?.method === 'OPTIONS') {
    return { statusCode: 200, headers, body: '' };
  }

  try {
    const body = JSON.parse(event.body || '{}');

    if (!body.to) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Recipient email is required.' }) };
    }

    const templateName = TEMPLATE_NAMES[body.reportType] || body.reportType;
    const dateStr = body.submittedAt ? new Date(body.submittedAt).toLocaleDateString() : 'Today';

    const command = new SendEmailCommand({
      Source: FROM_EMAIL,
      Destination: {
        ToAddresses: [body.to],
      },
      Message: {
        Subject: {
          Data: `Titan Mining - ${templateName} Report - ${dateStr}`,
        },
        Body: {
          Html: {
            Data: generateEmailHtml(body),
          },
        },
      },
    });

    await ses.send(command);

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ success: true, message: 'Email sent successfully.' }),
    };
  } catch (error: any) {
    console.error('Email send error:', error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: 'Failed to send email.', detail: error.message }),
    };
  }
};
